# Generated by Django 2.1.14 on 2021-01-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0009_auto_20200421_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSFScheme',
            fields=[
                ('id', models.AutoField(db_column='SCH_ID', primary_key=True, serialize=False)),
                ('SCH_NAME', models.CharField(db_column='SCH_NAME', max_length=100)),
                ('SCH_NAME_ENG', models.CharField(db_column='SCH_NAME_ENG', max_length=100)),
                ('VISIT_TYPE', models.CharField(db_column='VISIT_TYPE', max_length=150)),
                ('ENTRY_BY', models.CharField(db_column='ENTRY_BY', max_length=10)),
                ('ENTRY_DATE', models.BooleanField(db_column='ENTRY_DATE', default=False)),
                ('R_STATUS', models.DateTimeField(blank=True, db_column='R_STATUS', null=True)),
                ('SCHAPP_ID', models.IntegerField(blank=True, db_column='SCHAPP_ID', null=True)),
            ],
            options={
                'db_table': 'tblSSFSchemes',
            },
        ),
    ]
