# Generated by Django 2.1.14 on 2021-02-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0010_ssfscheme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssfscheme',
            old_name='id',
            new_name='SCH_ID',
        ),
    ]
