# Generated by Django 2.1.14 on 2021-02-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0011_auto_20210221_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssfscheme',
            old_name='SCH_ID',
            new_name='id',
        ),
    ]
