# Generated by Django 2.1.14 on 2021-02-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0012_auto_20210221_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssfscheme',
            name='SCH_ID',
            field=models.IntegerField(blank=True, db_column='SCH_ID', null=True),
        ),
        migrations.AlterField(
            model_name='ssfscheme',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
