# Generated by Django 2.1.14 on 2021-02-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0014_auto_20210222_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssfscheme',
            name='SCH_ID',
            field=models.IntegerField(db_column='SCH_ID', default=0),
        ),
        migrations.AlterField(
            model_name='ssfscheme',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
